# questions.py

QUESTION_BANK = {
    "Python": {
        "beginner": [
            {"question": "خروجی print(2**3) چیست؟", "options": ["6", "8", "9", "5"], "correct": 1},
            {"question": "کدام نوع داده برای اعداد صحیح استفاده می‌شود؟", "options": ["float", "int", "str", "list"], "correct": 1},
            {"question": "برای ایجاد لیست خالی از کدام دستور استفاده می‌شود؟", "options": ["[]", "{}", "()", "<>"], "correct": 0},
            {"question": "تابع len() چه کاری انجام می‌دهد؟", "options": ["طول رشته/لیست را برمی‌گرداند", "بزرگترین عدد را می‌دهد", "عدد را گرد می‌کند", "نوع متغیر را چک می‌کند"], "correct": 0},
            {"question": "کدام گزینه یک کامنت در پایتون است؟", "options": ["// این یک کامنت است", "# این یک کامنت است", "/* این یک کامنت است */", "<!-- این یک کامنت است -->"], "correct": 1},
            {"question": "خروجی print(\"Hello\"[0]) چیست؟", "options": ["H", "e", "l", "o"], "correct": 0},
            {"question": "کدام عملگر برای جمع استفاده می‌شود؟", "options": ["+", "-", "*", "/"], "correct": 0},
            {"question": "تابع print(type(5)) چه چیزی چاپ می‌کند؟", "options": ["<class 'int'>", "<class 'str'>", "<class 'float'>", "5"], "correct": 0},
            {"question": "حلقه for در پایتون روی چه چیزی تکرار می‌کند؟", "options": ["اعداد", "رشته‌ها", "عناصر یک iterable", "اندیس‌ها"], "correct": 2},
            {"question": "علامت مساوی (=) در پایتون چه معنایی دارد؟", "options": ["مقایسه برابری", "تخصیص مقدار", "بررسی نوع", "هیچکدام"], "correct": 1},
            {"question": "خروجی 3 + 2 * 2 چیست؟", "options": ["10", "7", "8", "5"], "correct": 1},
            {"question": "دستور input() چه نوع داده‌ای برمی‌گرداند؟", "options": ["int", "float", "str", "bool"], "correct": 2},
            {"question": "برای حذف فاصله‌های ابتدا و انتهای یک رشته از کدام متد استفاده می‌شود؟", "options": [".strip()", ".trim()", ".clean()", ".remove()"], "correct": 0},
            {"question": "لیست‌ها با چه نمادی تعریف می‌شوند؟", "options": ["()", "[]", "{}", "<>"], "correct": 1},
            {"question": "مقدار True در پایتون چه نوع داده‌ای است؟", "options": ["int", "bool", "str", "NoneType"], "correct": 1},
            {"question": "کدام یک حلقه بی‌نهایت می‌سازد؟", "options": ["while True:", "for i in range(10):", "while False:", "if True:"], "correct": 0},
            {"question": "تابع str(5) چه خروجی دارد؟", "options": ["5", "'5'", "int", "float"], "correct": 1},
            {"question": "برای اضافه کردن آیتم به انتهای لیست از کدام متد استفاده می‌شود؟", "options": [".add()", ".insert()", ".append()", ".extend()"], "correct": 2},
            {"question": "کدام گزینه یک عدد اعشاری (float) است؟", "options": ["5", "5.0", "'5'", "True"], "correct": 1},
            {"question": "خروجی bool([]) چیست؟", "options": ["True", "False", "Error", "None"], "correct": 1},
            {"question": "برای تبدیل یک عدد به رشته از کدام تابع استفاده می‌شود؟", "options": ["int()", "str()", "float()", "bool()"], "correct": 1},
            {"question": "کدام یک نام یک کتابخانه استاندارد پایتون است؟", "options": ["math", "numpy", "pandas", "requests"], "correct": 0},
            {"question": "دستور break در حلقه چه کاری انجام می‌دهد؟", "options": ["حلقه را متوقف و خارج می‌شود", "از دور جاری عبور می‌کند", "حلقه را ری‌استارت می‌کند", "خطا ایجاد می‌کند"], "correct": 0},
            {"question": "برای ایجاد یک رشته چندخطی از چه علامتی استفاده می‌شود؟", "options": ["\"\"\" یا '''", "//", "/*", "--"], "correct": 0},
            {"question": "خروجی 10 % 3 چیست؟", "options": ["1", "3", "0", "10"], "correct": 0},
            {"question": "کدام گزینه یک immutable (تغییرناپذیر) است؟", "options": ["list", "dict", "tuple", "set"], "correct": 2},
            {"question": "برای حذف یک عنصر از لیست با استفاده از مقدار آن از کدام متد استفاده می‌شود؟", "options": [".pop()", ".remove()", ".delete()", ".clear()"], "correct": 1},
            {"question": "خروجی print(1 == 1.0) چیست؟", "options": ["True", "False", "Error", "1"], "correct": 0},
            {"question": "کدام یک یک environment مجازی در پایتون ایجاد می‌کند؟", "options": ["python -m venv myenv", "python virtual myenv", "venv create", "mkvirtualenv"], "correct": 0},
            {"question": "تابع range(5) چه چیزی برمی‌گرداند؟", "options": ["[0,1,2,3,4]", "[1,2,3,4,5]", "[0,1,2,3,4,5]", "یک شیء range"], "correct": 3},
        ],
        "intermediate": [
            {"question": "خروجی کد زیر چیست؟\n```python\nx = [1,2,3]\ny = x\ny.append(4)\nprint(x)\n```", "options": ["[1,2,3]", "[1,2,3,4]", "[1,2,4]", "Error"], "correct": 1},
            {"question": "کلیدواژه def برای چه کاری استفاده می‌شود؟", "options": ["تعریف متغیر", "تعریف تابع", "تعریف کلاس", "ایجاد حلقه"], "correct": 1},
            {"question": "برای خواندن فایل متنی از کدام تابع استفاده می‌شود؟", "options": ["read()", "write()", "open()", "input()"], "correct": 2},
            {"question": "کدام متد برای اضافه کردن آیتم به انتهای لیست استفاده می‌شود؟", "options": [".add()", ".insert()", ".extend()", ".append()"], "correct": 3},
            {"question": "خروجی type(3.14) چیست؟", "options": ["<class 'int'>", "<class 'float'>", "<class 'str'>", "<class 'complex'>"], "correct": 1},
            {"question": "کدام یک tuple می‌سازد؟", "options": ["(1,2,3)", "[1,2,3]", "{1,2,3}", "<1,2,3>"], "correct": 0},
            {"question": "حلقه for در پایتون چگونه کار می‌کند؟", "options": ["شمارشی", "بر اساس اندیس", "روی عناصر یک iterable", "تا بی‌نهایت"], "correct": 2},
            {"question": "برای ایجاد دیکشنری خالی از چه علامتی استفاده می‌شود؟", "options": ["{}", "[]", "()", "<>"], "correct": 0},
            {"question": "خروجی len([1,2,3,4]) چیست؟", "options": ["3", "4", "5", "1"], "correct": 1},
            {"question": "تابع len در دیکشنری چه چیزی را برمی‌گرداند؟", "options": ["تعداد کلیدها", "تعداد مقادیر", "مجموع کلید و مقدار", "اندیس آخرین عنصر"], "correct": 0},
            {"question": "برای حذف یک کلید از دیکشنری از چه دستوری استفاده می‌شود؟", "options": ["del dict[key]", "dict.remove(key)", "dict.pop(key)", "هر دو گزینه ۱ و ۳"], "correct": 3},
            {"question": "خروجی bool([]) چیست؟", "options": ["True", "False", "Error", "None"], "correct": 1},
            {"question": "متد .split() روی رشته چه کاری انجام می‌دهد؟", "options": ["رشته را به لیست تبدیل می‌کند", "لیست را به رشته تبدیل می‌کند", "فاصله‌ها را حذف می‌کند", "رشته را معکوس می‌کند"], "correct": 0},
            {"question": "برای ایجاد یک کپی از لیست از کدام روش استفاده می‌شود؟", "options": ["list2 = list1", "list2 = list1.copy()", "list2 = copy(list1)", "هر دو گزینه ۲ و ۳"], "correct": 3},
            {"question": "کدام یک برای باز کردن فایل و بستن خودکار آن استفاده می‌شود؟", "options": ["open()", "with open() as f:", "file()", "read()"], "correct": 1},
            {"question": "تابع lambda در پایتون چیست؟", "options": ["یک تابع ناشناس کوچک", "یک ماژول", "یک نوع حلقه", "یک دکوراتور"], "correct": 0},
            {"question": "خروجی list(range(3)) چیست؟", "options": ["[0,1,2]", "[1,2,3]", "[0,1,2,3]", "[3]"], "correct": 0},
            {"question": "کدام عملگر برای مقایسه برابری استفاده می‌شود؟", "options": ["=", "==", "===", "!="], "correct": 1},
            {"question": "برای تبدیل یک عدد به رشته از کدام تابع استفاده می‌شود؟", "options": ["int()", "str()", "float()", "bool()"], "correct": 1},
            {"question": "خروجی 'hello'.upper() چیست؟", "options": ["HELLO", "hello", "Hello", "hELLO"], "correct": 0},
            {"question": "خروجی bool('') چیست؟", "options": ["True", "False", "Error", "None"], "correct": 1},
            {"question": "تابع zip چه کاری انجام می‌دهد؟", "options": ["دو لیست را ادغام می‌کند", "عناصر چند iterable را جفت می‌کند", "فایل‌ها را فشرده می‌کند", "رشته‌ها را ترکیب می‌کند"], "correct": 1},
            {"question": "برای اضافه کردن چند عنصر به انتهای لیست از چه متدی استفاده می‌شود؟", "options": [".extend()", ".append()", ".insert()", ".concat()"], "correct": 0},
            {"question": "کدام یک یک mutable (تغییرپذیر) است؟", "options": ["tuple", "string", "list", "int"], "correct": 2},
            {"question": "خروجی 5 // 2 چیست؟", "options": ["2.5", "2", "3", "10"], "correct": 1},
            {"question": "کدام یک یک built-in function در پایتون نیست؟", "options": ["print", "len", "sum", "main"], "correct": 3},
            {"question": "برای ایجاد یک دیکشنری با کلیدهای پیش‌فرض از چه متدی استفاده می‌شود؟", "options": [".get()", ".setdefault()", ".pop()", ".update()"], "correct": 1},
            {"question": "خروجی 'python'[1:4] چیست؟", "options": ["yth", "ytho", "pyt", "tho"], "correct": 0},
            {"question": "کدام یک ماژول استاندارد برای کار با عبارات باقاعده است؟", "options": ["re", "regex", "pyre", "relib"], "correct": 0},
            {"question": "تابع enumerate چه کاری انجام می‌دهد؟", "options": ["اندیس و مقدار را برمی‌گرداند", "لیست را مرتب می‌کند", "تعداد عناصر را می‌شمارد", "رشته را به عدد تبدیل می‌کند"], "correct": 0},
        ],
        "advanced": [
            {"question": "دکوراتور (decorator) در پایتون چیست؟", "options": ["نوعی حلقه", "یک تابع که تابع دیگر را می‌گیرد و توسعه می‌دهد", "ماژول استاندارد", "شیء گرافیکی"], "correct": 1},
            {"question": "کلیدواژه yield چه کاری انجام می‌دهد؟", "options": ["مقدار را برمی‌گرداند و تابع را پایان می‌دهد", "generator می‌سازد", "حلقه را می‌شکند", "لیست برمی‌گرداند"], "correct": 1},
            {"question": "مفهوم GIL در پایتون چیست؟", "options": ["Global Interpreter Lock", "Great Integrated Language", "General Input Library", "Garbage Interpreter Lock"], "correct": 0},
            {"question": "کدام یک یک context manager است؟", "options": ["تابع lambda", "کلاسی با متدهای __enter__ و __exit__", "دستور with", "ماژول os"], "correct": 1},
            {"question": "خروجی کد زیر چیست؟\n```python\nprint(list(map(lambda x: x*2, [1,2,3])))\n```", "options": ["[2,4,6]", "[1,4,9]", "[3,6,9]", "Error"], "correct": 0},
            {"question": "کدام یک برای ارث‌بری چندگانه استفاده می‌شود؟", "options": ["class Child(Base1):", "class Child(Base1, Base2):", "class Child(Base1(Base2)):", "class Child(Base1, Base2, Base3)"], "correct": 1},
            {"question": "متد __str__ در یک کلاس چه وظیفه‌ای دارد؟", "options": ["تبدیل شیء به رشته", "مقایسه دو شیء", "ایجاد شیء جدید", "حذف شیء"], "correct": 0},
            {"question": "کتابخانه asyncio برای چه منظوری استفاده می‌شود؟", "options": ["محاسبات ریاضی", "برنامه‌نویسی ناهمگام", "رابط گرافیکی", "کار با فایل"], "correct": 1},
            {"question": "تفاوت list و tuple چیست؟", "options": ["list تغییرپذیر است و tuple تغییرناپذیر", "list مرتب نیست", "tuple سرعت کمتری دارد", "list از حافظه بیشتری استفاده می‌کند"], "correct": 0},
            {"question": "کدام ماژول برای کار با عبارات با قاعده (regex) استفاده می‌شود؟", "options": ["regex", "re", "reg", "pyre"], "correct": 1},
            {"question": "برای نصب یک کتابخانه خارجی از کدام دستور استفاده می‌شود؟", "options": ["install", "pip install", "add", "library"], "correct": 1},
            {"question": "کدام یک برای ایجاد یک virtual environment استفاده می‌شود؟", "options": ["venv", "virtual", "env", "python -m venv"], "correct": 3},
            {"question": "در مدیریت استثناها، کدام بلاک همیشه اجرا می‌شود؟", "options": ["try", "except", "finally", "else"], "correct": 2},
            {"question": "تابع zip چه کاری انجام می‌دهد؟", "options": ["دو لیست را ادغام می‌کند", "عناصر چند iterable را جفت می‌کند", "فایل‌ها را فشرده می‌کند", "رشته‌ها را ترکیب می‌کند"], "correct": 1},
            {"question": "مفهوم *args در تعریف تابع چیست؟", "options": ["آرگومان‌های کلیدواژه", "تعداد متغیری از آرگومان‌های غیرکلیدواژه", "آرگومان پیش‌فرض", "دکوراتور"], "correct": 1},
            {"question": "کدام یک یک immutable است؟", "options": ["list", "dict", "tuple", "set"], "correct": 2},
            {"question": "برای ایجاد یک set خالی از چه دستوری استفاده می‌شود؟", "options": ["{}", "set()", "[]", "()"], "correct": 1},
            {"question": "متد .get() در دیکشنری چه مزیتی دارد؟", "options": ["سرعت بالاتر", "اگر کلید نباشد، خطا نمی‌دهد", "مقدار را حذف می‌کند", "کلید جدید اضافه می‌کند"], "correct": 1},
            {"question": "کدام یک برای مرتب‌سازی لیست استفاده می‌شود؟", "options": [".sort()", ".order()", ".arrange()", ".sorted()"], "correct": 0},
            {"question": "خروجی bool(0) چیست؟", "options": ["True", "False", "Error", "0"], "correct": 1},
            {"question": "کدام یک یک generator expression است؟", "options": ["(x for x in range(10))", "[x for x in range(10)]", "{x for x in range(10)}", "lambda x: x"], "correct": 0},
            {"question": "کتابخانه requests برای چه کاری استفاده می‌شود؟", "options": ["درخواست‌های HTTP", "محاسبات ریاضی", "کار با پایگاه داده", "ساخت رابط گرافیکی"], "correct": 0},
            {"question": "مفهوم monkey patching در پایتون چیست؟", "options": ["تغییر رفتار کلاس/ماژول در زمان اجرا", "برطرف کردن باگ", "نوعی تست نرم‌افزار", "ترجمه کد"], "correct": 0},
            {"question": "کدام یک برای اجرای یک تابع در یک thread جدا استفاده می‌شود؟", "options": ["threading.Thread", "multiprocessing.Process", "asyncio.run", "exec"], "correct": 0},
            {"question": "تزئین‌گر @staticmethod چه کاری انجام می‌دهد؟", "options": ["متد را به یک متد کلاس تبدیل می‌کند", "متد را مستقل از نمونه می‌کند", "متد را تبدیل به property می‌کند", "متد را غیرقابل تغییر می‌کند"], "correct": 1},
            {"question": "خروجی isinstance(True, int) چیست؟", "options": ["True", "False", "Error", "None"], "correct": 0},
            {"question": "برای ایجاد یک دیکشنری با کلیدهای پیش‌فرض و یک تابع سازنده از چه کلاسی استفاده می‌شود؟", "options": ["defaultdict", "OrderedDict", "Counter", "ChainMap"], "correct": 0},
            {"question": "کدام یک یک async framework محبوب برای پایتون است؟", "options": ["Flask", "Django", "FastAPI", "Pyramid"], "correct": 2},
            {"question": "مفهوم metaclass در پایتون چیست؟", "options": ["کلاسی که کلاس‌های دیگر را می‌سازد", "نوعی دکوراتور", "روشی برای ارث‌بری", "کتابخانه خارجی"], "correct": 0},
            {"question": "تابع super() چه کاری انجام می‌دهد؟", "options": ["کلاس والد را صدا می‌زند", "نمونه جدید می‌سازد", "متدهای کلاس فرزند را اجرا می‌کند", "هیچکدام"], "correct": 0},
        ]
    },
    "JavaScript": {
        "beginner": [
            {"question": "خروجی console.log(2 + '2') چیست؟", "options": ["4", "'22'", "22", "Error"], "correct": 1},
            {"question": "کدام کلمه کلیدی برای تعریف متغیر در ES6 استفاده می‌شود؟", "options": ["var", "let", "const", "هر دو let و const"], "correct": 3},
            {"question": "برای چاپ چیزی در کنسول از کدام دستور استفاده می‌شود؟", "options": ["print()", "console.log()", "echo", "alert()"], "correct": 1},
            {"question": "کدام یک نوع داده اولیه (primitive) نیست؟", "options": ["string", "number", "boolean", "object"], "correct": 3},
            {"question": "علامت انتساب در جاوااسکریپت چیست؟", "options": ["=", "==", "===", "="], "correct": 0},
            {"question": "خروجی typeof 'hello' چیست؟", "options": ["'string'", "'number'", "'object'", "'undefined'"], "correct": 0},
            {"question": "برای تعریف یک آرایه خالی از چه علامتی استفاده می‌شود؟", "options": ["[]", "{}", "()", "<>"], "correct": 0},
            {"question": "کدام متد طول یک آرایه را برمی‌گرداند؟", "options": [".length", ".size()", ".count()", ".len()"], "correct": 0},
            {"question": "حلقه for در جاوااسکریپت چگونه نوشته می‌شود؟", "options": ["for (i = 0; i < 10; i++)", "for (i; i<10; i++)", "for (let i of array)", "همه موارد"], "correct": 3},
            {"question": "خروجی 2 == '2' چیست؟", "options": ["true", "false", "Error", "undefined"], "correct": 0},
            {"question": "خروجی 2 === '2' چیست؟", "options": ["true", "false", "Error", "undefined"], "correct": 1},
            {"question": "برای اضافه کردن یک عنصر به انتهای آرایه از چه متدی استفاده می‌شود؟", "options": [".push()", ".pop()", ".shift()", ".unshift()"], "correct": 0},
            {"question": "کدام تابع یک پنجره هشدار نمایش می‌دهد؟", "options": ["alert()", "prompt()", "confirm()", "console.log()"], "correct": 0},
            {"question": "خروجی Boolean('') چیست؟", "options": ["true", "false", "Error", "''"], "correct": 1},
            {"question": "برای تبدیل یک رشته به عدد صحیح از کدام تابع استفاده می‌شود؟", "options": ["parseInt()", "parseFloat()", "Number()", "هر دو parseInt و Number"], "correct": 3},
            {"question": "کدام یک یک رویداد (event) در جاوااسکریپت است؟", "options": ["click", "hover", "load", "همه موارد"], "correct": 3},
            {"question": "متد .toUpperCase() چه کاری انجام می‌دهد؟", "options": ["حروف را بزرگ می‌کند", "حروف را کوچک می‌کند", "رشته را معکوس می‌کند", "فضاها را حذف می‌کند"], "correct": 0},
            {"question": "کدام یک یک حلقه در جاوااسکریپت نیست؟", "options": ["for", "while", "do...while", "loop"], "correct": 3},
            {"question": "خروجی typeof null چیست؟", "options": ["'null'", "'undefined'", "'object'", "'null'"], "correct": 2},
            {"question": "برای انتخاب یک عنصر با id مشخص از DOM از چه متدی استفاده می‌شود؟", "options": ["getElementById()", "querySelector()", "getElementsByClassName()", "هر دو ۱ و ۲"], "correct": 3},
            {"question": "کدام یک یک فریمورک فرانت‌اند جاوااسکریپت است؟", "options": ["React", "Django", "Flask", "Laravel"], "correct": 0},
            {"question": "برای ایجاد یک تابع در جاوااسکریپت از کدام کلیدواژه استفاده می‌شود؟", "options": ["def", "function", "func", "method"], "correct": 1},
            {"question": "خروجی 5 % 2 چیست؟", "options": ["1", "2", "2.5", "0"], "correct": 0},
            {"question": "متد .split() روی رشته چه کاری انجام می‌دهد؟", "options": ["رشته را به آرایه تبدیل می‌کند", "آرایه را به رشته تبدیل می‌کند", "رشته را جستجو می‌کند", "بخشی از رشته را برمی‌گرداند"], "correct": 0},
            {"question": "برای جلوگیری از رفتار پیش‌فرض یک رویداد از چه متدی استفاده می‌شود؟", "options": ["preventDefault()", "stopPropagation()", "return false", "cancel()"], "correct": 0},
            {"question": "کدام یک یک مقدار falsy نیست؟", "options": ["0", "''", "null", "'false'"], "correct": 3},
            {"question": "تابع isNaN('hello') چه چیزی برمی‌گرداند؟", "options": ["true", "false", "Error", "'hello'"], "correct": 0},
            {"question": "برای تعریف یک متغیر ثابت در ES6 از چه کلیدواژه‌ای استفاده می‌شود؟", "options": ["let", "var", "const", "static"], "correct": 2},
            {"question": "خروجی console.log(1 + 1 + '1') چیست؟", "options": ["'21'", "3", "'111'", "Error"], "correct": 0},
            {"question": "کدام متد اولین عنصر یک آرایه را حذف می‌کند؟", "options": [".pop()", ".shift()", ".unshift()", ".splice()"], "correct": 1},
        ],
        "intermediate": [
            {"question": "خروجی [1,2,3].map(x => x*2) چیست؟", "options": ["[2,4,6]", "[1,4,9]", "[3,6,9]", "Error"], "correct": 0},
            {"question": "متد filter() چه کاری انجام می‌دهد؟", "options": ["آرایه را پیمایش می‌کند", "عناصر شرط‌دار را برمی‌گرداند", "همه عناصر را تغییر می‌دهد", "آرایه را مرتب می‌کند"], "correct": 1},
            {"question": "برای ایجاد یک شیء جدید در جاوااسکریپت از چه علامتی استفاده می‌شود؟", "options": ["{}", "[]", "new Object()", "هر دو ۱ و ۳"], "correct": 3},
            {"question": "کدام یک یک تابع callback را می‌پذیرد؟", "options": ["setTimeout", "forEach", "addEventListener", "همه موارد"], "correct": 3},
            {"question": "خروجی typeof function(){} چیست؟", "options": ["'function'", "'object'", "'method'", "'undefined'"], "correct": 0},
            {"question": "مفهوم hoisting در جاوااسکریپت چیست؟", "options": ["انتقال تعاریف به بالای حوزه", "بالا بردن خطاها", "افزایش عملکرد", "نوعی cache"], "correct": 0},
            {"question": "تفاوت let و var چیست؟", "options": ["let حوزه بلوکی دارد", "var حوزه بلوکی دارد", "let قابل تغییر نیست", "var فقط در ES6 معتبر است"], "correct": 0},
            {"question": "متد reduce() چه خروجی می‌دهد؟", "options": ["یک مقدار واحد", "یک آرایه", "یک شیء", "undefined"], "correct": 0},
            {"question": "کدام یک یک promise را برمی‌گرداند؟", "options": ["fetch()", "setTimeout()", "alert()", "console.log()"], "correct": 0},
            {"question": "برای مدیریت یک promise موفق از کدام متد استفاده می‌شود؟", "options": [".then()", ".catch()", ".finally()", ".success()"], "correct": 0},
            {"question": "خروجی NaN === NaN چیست؟", "options": ["true", "false", "Error", "undefined"], "correct": 1},
            {"question": "کدام یک یک رویداد ماوس نیست؟", "options": ["click", "mouseover", "keydown", "mousemove"], "correct": 2},
            {"question": "برای ایجاد یک کپی عمیق از یک شیء از چه روشی استفاده می‌شود؟", "options": ["JSON.parse(JSON.stringify(obj))", "Object.assign({}, obj)", "spread operator", "همه موارد"], "correct": 0},
            {"question": "متد bind() چه کاری انجام می‌دهد؟", "options": ["this را به یک تابع می‌چسباند", "دو شیء را ادغام می‌کند", "یک تابع را صدا می‌زند", "رشته را متصل می‌کند"], "correct": 0},
            {"question": "کدام یک یک ماژول استاندارد در Node.js است؟", "options": ["fs", "http", "path", "همه موارد"], "correct": 3},
            {"question": "برای export یک تابع در ماژول ES6 از چه کلمه کلیدی استفاده می‌شود؟", "options": ["export", "module.exports", "exports", "require"], "correct": 0},
            {"question": "مفهوم event delegation چیست؟", "options": ["واگذاری رویداد به والد", "تکثیر رویداد", "حذف رویدادها", "ایجاد رویداد جدید"], "correct": 0},
            {"question": "کدام یک یک framework تست برای جاوااسکریپت است؟", "options": ["Jest", "Mocha", "Jasmine", "همه موارد"], "correct": 3},
            {"question": "برای تبدیل یک شیء به JSON از کدام متد استفاده می‌شود؟", "options": ["JSON.stringify()", "JSON.parse()", "toString()", "toJSON()"], "correct": 0},
            {"question": "خروجی 0.1 + 0.2 == 0.3 چیست؟", "options": ["true", "false", "Error", "undefined"], "correct": 1},
            {"question": "کدام یک برای اجرای کد با تأخیر استفاده می‌شود؟", "options": ["setInterval", "setTimeout", "requestAnimationFrame", "delay"], "correct": 1},
            {"question": "خروجی [1,2,3].indexOf(2) چیست؟", "options": ["1", "2", "0", "-1"], "correct": 0},
            {"question": "کدام متد یک رشته را به عدد اعشاری تبدیل می‌کند؟", "options": ["parseInt()", "parseFloat()", "Number()", "همه موارد"], "correct": 1},
            {"question": "برای ایجاد یک شیء از یک کلاس از کدام کلیدواژه استفاده می‌شود؟", "options": ["new", "create", "instance", "build"], "correct": 0},
            {"question": "مفهوم currying در جاوااسکریپت چیست؟", "options": ["تبدیل تابع چندآرگومانی به زنجیره توابع تک‌آرگومانی", "اضافه کردن طعم به کد", "بهینه‌سازی حافظه", "نوعی closure"], "correct": 0},
            {"question": "کدام یک یک کتابخانه مدیریت state در React است؟", "options": ["Redux", "MobX", "Zustand", "همه موارد"], "correct": 3},
            {"question": "خروجی typeof NaN چیست؟", "options": ["'number'", "'NaN'", "'undefined'", "'object'"], "correct": 0},
            {"question": "برای حذف آخرین عنصر یک آرایه از کدام متد استفاده می‌شود؟", "options": [".pop()", ".shift()", ".splice()", ".slice()"], "correct": 0},
            {"question": "کدام یک یک CSS preprocessor نیست؟", "options": ["Sass", "Less", "Stylus", "PostCSS"], "correct": 3},
            {"question": "خروجی Boolean('false') چیست؟", "options": ["true", "false", "Error", "'false'"], "correct": 0},
        ],
        "advanced": [
            {"question": "مفهوم Closure در جاوااسکریپت چیست؟", "options": [
                "تابعی که به متغیرهای خارج از خود دسترسی دارد",
                "روشی برای ارث‌بری",
                "نوعی حلقه",
                "کتابخانه استاندارد"
            ], "correct": 0},
            {"question": "تفاوت call و apply چیست؟", "options": ["call آرگومان‌ها را جداگانه می‌گیرد، apply به‌صورت آرایه", "هر دو یکی هستند", "apply فقط برای توابع constructor", "call سریع‌تر است"], "correct": 0},
            {"question": "متد Object.create() چه کاری انجام می‌دهد؟", "options": ["یک شیء جدید با prototype مشخص می‌سازد", "یک کپی عمیق ایجاد می‌کند", "دو شیء را ادغام می‌کند", "یک کلاس تعریف می‌کند"], "correct": 0},
            {"question": "کدام یک یک تابع خالص (pure function) است؟", "options": ["function add(a,b) { return a+b; }", "function rand() { return Math.random(); }", "function log(msg) { console.log(msg); }", "function now() { return Date.now(); }"], "correct": 0},
            {"question": "مفهوم prototype chain در جاوااسکریپت چیست؟", "options": ["زنجیره ارث‌بری اشیاء", "روشی برای حلقه", "لیست متدهای یک شیء", "ترتیب فراخوانی توابع"], "correct": 0},
            {"question": "کدام یک یک ماژول native در ES6 است؟", "options": ["import/export", "require/module.exports", "define", "use"], "correct": 0},
            {"question": "برای ایجاد یک iterator سفارشی از کدام protocol استفاده می‌شود؟", "options": ["Symbol.iterator", "Symbol.asyncIterator", "Symbol.hasInstance", "Symbol.toPrimitive"], "correct": 0},
            {"question": "کدام یک یک design pattern در جاوااسکریپت است؟", "options": ["Module", "Observer", "Singleton", "همه موارد"], "correct": 3},
            {"question": "تابع debounce چه کاری انجام می‌دهد؟", "options": ["اجرای تابع را تا پایان توالی رویدادها به تأخیر می‌اندازد", "تعداد فراخوانی‌ها را محدود می‌کند", "تابع را لغو می‌کند", "حافظه را پاک می‌کند"], "correct": 0},
            {"question": "متد proxy در جاوااسکریپت چه کاربردی دارد؟", "options": ["ایجاد یک لایه میانی برای کنترل دسترسی به شیء", "اجرای کد روی سرور", "کپی عمیق", "مدیریت خطاها"], "correct": 0},
            {"question": "کدام یک یک کتابخانه مدیریت state پیشرفته برای React نیست؟", "options": ["Recoil", "Jotai", "Vuex", "Zustand"], "correct": 2},
            {"question": "مفهوم tree shaking در webpack چیست؟", "options": ["حذف کدهای استفاده‌نشده", "بهینه‌سازی تصاویر", "فشرده‌سازی فایل‌ها", "تقسیم کد"], "correct": 0},
            {"question": "برای اجرای یک تابع async و منتظر ماندن از چه کلیدواژه‌ای استفاده می‌شود؟", "options": ["await", "yield", "async", "defer"], "correct": 0},
            {"question": "کدام یک یک runtime جاوااسکریپت سمت سرور است؟", "options": ["Node.js", "Deno", "Bun", "همه موارد"], "correct": 3},
            {"question": "مفهوم event loop در جاوااسکریپت چیست؟", "options": ["مدل همگام‌سازی اجرای کد", "حلقه تکرار رویدادها", "مدیریت خطاها", "کتابخانه خارجی"], "correct": 1},
            {"question": "خروجی Promise.resolve(1).then(console.log) چیست؟", "options": ["1", "Promise {<fulfilled>: undefined}", "Promise", "undefined"], "correct": 0},
            {"question": "کدام یک یک ابزار ساخت (build tool) جاوااسکریپت است؟", "options": ["Webpack", "Vite", "Parcel", "همه موارد"], "correct": 3},
            {"question": "تفاوت null و undefined چیست؟", "options": ["null یعنی عدم وجود، undefined یعنی تعریف نشده", "هر دو یکی هستند", "undefined مخصوص اشیاء است", "null برای متغیرهای محلی است"], "correct": 0},
            {"question": "متد Symbol.toPrimitive چه کاری انجام می‌دهد؟", "options": ["تبدیل شیء به مقدار اولیه", "ایجاد iterator", "مدیریت حافظه", "آرایه‌سازی"], "correct": 0},
            {"question": "کدام یک یک کتابخانه برای مدیریت فرم در React است؟", "options": ["Formik", "React Hook Form", "Redux Form", "همه موارد"], "correct": 3},
            {"question": "مفهوم service worker در مرورگر چیست؟", "options": ["اسکریپت پس‌زمینه برای آفلاین و cache", "پردازش موازی", "ایجاد نخ جدید", "ارتباط با سرور"], "correct": 0},
            {"question": "برای تعریف یک ماژول CommonJS از چه روشی استفاده می‌شود؟", "options": ["require و module.exports", "import و export", "define", "use"], "correct": 0},
            {"question": "کدام یک یک تابع آرایه‌ای جدید در ES2023 است؟", "options": [".findLast()", ".toSorted()", ".toReversed()", "همه موارد"], "correct": 3},
            {"question": "مفهوم tail call optimization در جاوااسکریپت چیست؟", "options": ["بهینه‌سازی فراخوانی‌های بازگشتی انتهایی", "افزایش سرعت حلقه‌ها", "حذف متغیرهای بی‌استفاده", "فشرده‌سازی کد"], "correct": 0},
            {"question": "کدام یک برای مدیریت خطا در async/await استفاده می‌شود؟", "options": ["try/catch", ".catch()", "finally", "همه موارد"], "correct": 3},
            {"question": "خروجی [] + {} چیست؟", "options": ["'[object Object]'", "0", "undefined", "Error"], "correct": 0},
            {"question": "کدام یک یک کتابخانه نمودار برای جاوااسکریپت است؟", "options": ["Chart.js", "D3.js", "Plotly", "همه موارد"], "correct": 3},
            {"question": "مفهوم microtask در event loop چیست؟", "options": ["وظایفی که قبل از macrotask اجرا می‌شوند", "تسک‌های با اولویت پایین", "خطاهای جزئی", "callbackهای setTimeout"], "correct": 0},
            {"question": "برای تعریف یک getter در یک شیء از چه کلیدواژه‌ای استفاده می‌شود؟", "options": ["get", "set", "value", "access"], "correct": 0},
            {"question": "کدام یک یک runtime خطایابی بهتر ارائه می‌دهد؟", "options": ["TypeScript", "Flow", "JSDoc", "همه موارد"], "correct": 3},
        ]
    }
}

# زمان هر سطح (ثانیه)
TIMEOUTS = {"beginner": 8, "intermediate": 20, "advanced": 40}

# تعداد سوالات هر سطح
QUESTIONS_COUNT = {"beginner": 5, "intermediate": 7, "advanced": 10}